# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

modification_loc <- function(inx_name, K, mx_k) {
    .Call('_GENESIS_modification_loc', PACKAGE = 'GENESIS', inx_name, K, mx_k)
}

cpnorm <- function(x) {
    .Call('_GENESIS_cpnorm', PACKAGE = 'GENESIS', x)
}

sumfactorial <- function(n) {
    .Call('_GENESIS_sumfactorial', PACKAGE = 'GENESIS', n)
}

sumfactorial_rev <- function(n, k0) {
    .Call('_GENESIS_sumfactorial_rev', PACKAGE = 'GENESIS', n, k0)
}

cdnorm <- function(x, mean, sd, loglog) {
    .Call('_GENESIS_cdnorm', PACKAGE = 'GENESIS', x, mean, sd, loglog)
}

cdbinom <- function(k, size, prob, loglog) {
    .Call('_GENESIS_cdbinom', PACKAGE = 'GENESIS', k, size, prob, loglog)
}

cdmultinom3 <- function(k0, k1, k2, prob, loglog) {
    .Call('_GENESIS_cdmultinom3', PACKAGE = 'GENESIS', k0, k1, k2, prob, loglog)
}

loglikelihood <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call('_GENESIS_loglikelihood', PACKAGE = 'GENESIS', par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

weight <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call('_GENESIS_weight', PACKAGE = 'GENESIS', par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

weight_loglikelihood <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call('_GENESIS_weight_loglikelihood', PACKAGE = 'GENESIS', par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

update_pi1 <- function(w, Nstar, num_threads) {
    .Call('_GENESIS_update_pi1', PACKAGE = 'GENESIS', w, Nstar, num_threads)
}

onestep_varcomponent <- function(varcomponent, w, betahat, varbetahat, ldscore, Nstar, num_threads) {
    .Call('_GENESIS_onestep_varcomponent', PACKAGE = 'GENESIS', varcomponent, w, betahat, varbetahat, ldscore, Nstar, num_threads)
}

EM_func <- function(par_start, betahat, varbetahat, ldscore, Nstar, M, c0, eps1, eps2, eps3, eps, Meps, steps, num_threads, print, printfreq, stratification) {
    .Call('_GENESIS_EM_func', PACKAGE = 'GENESIS', par_start, betahat, varbetahat, ldscore, Nstar, M, c0, eps1, eps2, eps3, eps, Meps, steps, num_threads, print, printfreq, stratification)
}

Sk <- function(par, betahatk, varbetahatk, ldscorek, c0, Nstark) {
    .Call('_GENESIS_Sk', PACKAGE = 'GENESIS', par, betahatk, varbetahatk, ldscorek, c0, Nstark)
}

Ik <- function(par, betahatk, varbetahatk, ldscorek, c0, Nstark) {
    .Call('_GENESIS_Ik', PACKAGE = 'GENESIS', par, betahatk, varbetahatk, ldscorek, c0, Nstark)
}

S <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call('_GENESIS_S', PACKAGE = 'GENESIS', par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

SS <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call('_GENESIS_SS', PACKAGE = 'GENESIS', par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

I <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call('_GENESIS_I', PACKAGE = 'GENESIS', par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

mixture_components_marginal <- function(par, ldscore, c0, Nstar, num_threads) {
    .Call('_GENESIS_mixture_components_marginal', PACKAGE = 'GENESIS', par, ldscore, c0, Nstar, num_threads)
}

loglikelihood3 <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call('_GENESIS_loglikelihood3', PACKAGE = 'GENESIS', par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

weight3 <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call('_GENESIS_weight3', PACKAGE = 'GENESIS', par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

weight_loglikelihood3 <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call('_GENESIS_weight_loglikelihood3', PACKAGE = 'GENESIS', par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

update_p3 <- function(w, Nstar, num_threads) {
    .Call('_GENESIS_update_p3', PACKAGE = 'GENESIS', w, Nstar, num_threads)
}

onestep_varcomponent3 <- function(varcomponent, w, betahat, varbetahat, ldscore, Nstar, num_threads) {
    .Call('_GENESIS_onestep_varcomponent3', PACKAGE = 'GENESIS', varcomponent, w, betahat, varbetahat, ldscore, Nstar, num_threads)
}

EM_func3 <- function(par_start, lower_pi, upper_pi, betahat, varbetahat, ldscore, Nstar, M, c0, eps1, eps2, eps3, eps4, eps5, eps, Meps, steps, num_threads, print, printfreq, stratification) {
    .Call('_GENESIS_EM_func3', PACKAGE = 'GENESIS', par_start, lower_pi, upper_pi, betahat, varbetahat, ldscore, Nstar, M, c0, eps1, eps2, eps3, eps4, eps5, eps, Meps, steps, num_threads, print, printfreq, stratification)
}

Sk3 <- function(par, betahatk, varbetahatk, ldscorek, c0, Nstark) {
    .Call('_GENESIS_Sk3', PACKAGE = 'GENESIS', par, betahatk, varbetahatk, ldscorek, c0, Nstark)
}

Ik3 <- function(par, betahatk, varbetahatk, ldscorek, c0, Nstark) {
    .Call('_GENESIS_Ik3', PACKAGE = 'GENESIS', par, betahatk, varbetahatk, ldscorek, c0, Nstark)
}

S3 <- function(par, betahat, varbetahat, ldscore, c0, Nstar) {
    .Call('_GENESIS_S3', PACKAGE = 'GENESIS', par, betahat, varbetahat, ldscore, c0, Nstar)
}

SS3 <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call('_GENESIS_SS3', PACKAGE = 'GENESIS', par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

I3 <- function(par, betahat, varbetahat, ldscore, c0, Nstar, num_threads) {
    .Call('_GENESIS_I3', PACKAGE = 'GENESIS', par, betahat, varbetahat, ldscore, c0, Nstar, num_threads)
}

mixture_3components_marginal <- function(par, ldscore, c0, Nstar, num_threads) {
    .Call('_GENESIS_mixture_3components_marginal', PACKAGE = 'GENESIS', par, ldscore, c0, Nstar, num_threads)
}

